name: flutter_tindercard
description: Tinder(TanTan) Card Widget, fast way to have a high quality swap card widget in your flutter app.
version: 0.2.1
homepage: https://github.com/RiRa12621/flutter_tindercard_dart_3

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
